### ISSUE TITLE
Sample and documentation

### ISSUE THREAD

**Issue by eleonorarocchi** [Furrmidable-Crew/AnalytiBot#1]
It would be very useful to have concrete examples of use and instructions for use.

**Comment by pieroit** [comment]
Hi @eleonorarocchi this plugin is an experiment, not updated.
You can understand more about what it does by seeing hooks and tools in the code.
Thanks for asking ,:)

**Comment by eleonorarocchi** [comment]
Hi Piero, thank you for the answer. I'm doing some tests and experiments and trying different things, including this plugin. Let's see what comes out :-)

**Comment by zAlweNy26** [comment]
Hi, thanks for opening this issue, at the moment I'm busy and can't update this really old plugin (made when the plugin system first came out!), but if you want I accept PRs :)
